### ISSUE TITLE
Split out logs with >1 project on Comprehensive Report

### ISSUE THREAD

**Issue by baileyemily** [EnVisageConsulting/timelog#10]
If a log has >1 project, show each project log separately with the separate time.

This is important to ensure that other projects time do not get added in if Connie were to search by a Project and look at the total time.

E.g. Instead of "Project 1 and Project 2" with 2.0 hours, split into "Project 1" with 1.5 hours and "Project 2" with 0.5 hours.

**Comment by mjllewelyn** [comment]
I might be missing something, but I think this is fixed.
There are two tables, one with logs, and one with project logs. The project logs have each project separated into hours.

**Comment by dhuey** [comment]
I'm not sure about this one. I think it was initially for the "Comprehensive Report" (#9, maybe?), which doesn't exist yet, so I'm not sure how it could be fixed. Which two tables are you talking about?

**Comment by mjllewelyn** [comment]
From what I understand it might have been that if a log had more than one project, it was lumping them together and it would just have Project 1 and Project 2 with 2.0 hours and it didn't split it out into Project 1 with 1.5 hours and Project 2 with 0.5 hours. Which by my understanding it is doing that now, and you can filter to Project 1 and it says 1.5 hours. It could also be with the comprehensive report, and I just completely misunderstood this issue.

The two tables I'm talking about are db tables: the logs table and the project_logs table, which does split the projects out.
