### ISSUE TITLE
Forgot Password Emails Not Working

### ISSUE THREAD

**Issue by baileyemily** [EnVisageConsulting/timelog#11]
I tried out the "Forgot Password" password recovery email feature, and never received any emails to reset my password. 

Maybe it just isn't set up yet to send emails?

**Comment by baileyemily** [comment]
...and after doing that, now none of the users' passwords work :/ 
Even the ones that I didn't change at all.

**Comment by MicahBrown** [comment]
No outgoing email service has been set up yet. I'm not sure about the second thing you mentioned. I doubt the forgot password feature changed the passwords inadvertently.

**Comment by baileyemily** [comment]
Well, I'm not sure what it did...but I can't log into any of the accounts now :/

**Comment by baileyemily** [comment]
I just logged in as Admin. Maybe it was cached on my other computer?

**Comment by baileyemily** [comment]
Going to close this. I think it is working just fine.
