### ISSUE TITLE
Payroll report formatting

### ISSUE THREAD

**Issue by dhuey** [EnVisageConsulting/timelog#22]
<img width="1675" alt="Screen Shot 2020-01-08 at 1 00 37 PM" src="https://user-images.githubusercontent.com/26553688/72007361-1e2b1d00-3217-11ea-8f7d-ff315fb52390.png">
The last entry looks like it's trying to indent and add the date again on subsequent entries.

**Comment by mjllewelyn** [comment]
Looks like it's doing that since it's the same log entry, but a different project
