### ISSUE TITLE
Make default send address for admin emails admins' actual emails

### ISSUE THREAD

**Issue by dhuey** [EnVisageConsulting/timelog#28]
I've set it to my email address for now, so that way we don't spam Connie while we get everything set up. We'll just want to be sure we change it when we make this live.

**Comment by mjllewelyn** [comment]
@dhuey Is this done?

**Comment by dhuey** [comment]
Yeah, I just set it to go to Connie. If in the future you want to set it to send to all admins, you can do that as well.
