### ISSUE TITLE
Comprehensive report

### ISSUE THREAD

**Issue by mjllewelyn** [EnVisageConsulting/timelog#31]
On top of #9 I think Connie is wanting a report that is able to filter on both users and projects. Right now for the invoice report is filtered by project, then split up by user, so it is similar, but probably should make another report to be able to filter by both project and user.

**Comment by dhuey** [comment]
I'm having a hard time picturing what you mean here. Could you make a quick mockup of what you're thinking? Is it different than #10?

**Comment by mjllewelyn** [comment]
As I understand it, it's basically as the Invoice Report is now, but just being able to filter by User as well. I saw you said on #35 that the invoice should be sorted by report. So, the comprehensive report would be basically the invoice report showing all the Users and projects, and sorted by user. Now that I'm thinking about it, the payroll report may be what is wanted by being able to sort by user, I'm not sure
