### ISSUE TITLE
Set up Codeship for specs

### ISSUE THREAD

**Issue by mjllewelyn** [EnVisageConsulting/timelog#32]

**Comment by mjllewelyn** [comment]
I looked at setting up Codeship and looks like the owner of the repository has to give Codeship access. I'm not sure where the login info for that is. Probably is the same thing for Slack

**Comment by dhuey** [comment]
I think we decided we weren't going to do specs since it's a small enough project. It's also internal, so if something that looks funky goes out, clients don't see it
