### ISSUE TITLE
Set up Exports for Reports

### ISSUE THREAD

**Issue by mjllewelyn** [EnVisageConsulting/timelog#36]
I think it might be nice to have exports for the reports, especially the invoice report so that it would be easy to export it and send it.

**Comment by dhuey** [comment]
Are you thinking pdf exports?

**Comment by mjllewelyn** [comment]
Possibly. I don't know exactly what would be the best

**Comment by mjllewelyn** [comment]
Connie and I talked and we decided that since it works to click print and then save as PDF, there's no need to do a fancy PDF export. Also it works well to copy the data into Excel, so no need for a CSV file either.
