### ISSUE TITLE
Question: How many log entries should appear on Recent Logs?

### ISSUE THREAD

**Issue by agaug** [EnVisageConsulting/timelog#46]
I was looking at the recent logs page I wondered how many logs you wanted to have appear here. This is the log that I uploaded from my time log entries last week. 

![image](https://user-images.githubusercontent.com/33165589/77935056-8ddd0100-7276-11ea-90ae-8f5a44d7866b.png)

I also made some extra entries (not pictured). So far all of them have appeared on the main page, and it spans more than a week, from March 30 to March 18th. Was there a number of entries that should show? Or would it only show the entries up to a week ago?

**Comment by dhuey** [comment]
For all of our pagination, we use a package called Kaminari. We have it set to use all the default settings, which is to have 25 logs per page. So on the recent logs section, it's just the first page of the most recent logs (up to 25). This will show the same as the first page of the "View All Logs" page if no filters are applied.

We can edit this to be by time or number of logs if we think that would be best. Personally, I think the limit of 25 is okay.
