### ISSUE TITLE
Inconsistency on time log home page

### ISSUE THREAD

**Issue by agaug** [EnVisageConsulting/timelog#47]
Here is the link: http://ectimelog.herokuapp.com/
I'm logged in as Audrey Phillips 

Inconsistency between **Hours completed this week** (1.6 hrs) and **Number of hours by week** (1.5 hrs)

![image](https://user-images.githubusercontent.com/33165589/77938184-fa59ff00-727a-11ea-92c2-c051dbb7deb2.png)

**Comment by dhuey** [comment]
@mjllewelyn Do you want to take a look at this? It might be related to #24

**Comment by mjllewelyn** [comment]
I set the graph to round to the nearest .5, but I might see if I can round it to the nearest .1

**Comment by mjllewelyn** [comment]
@agaug It should be rounding to the nearest tenth like the "Hours Completed This Week" is. So it should be the same now

**Comment by dhuey** [comment]
Is this working the way we expect it to now?

**Comment by agaug** [comment]
@dhuey 
It's working well!
