### ISSUE TITLE
"Finish Current Log" time wrong over many days

### ISSUE THREAD

**Issue by agaug** [EnVisageConsulting/timelog#51]
I found this right after I logged in as Audrey Phillips, and I think it has to do with me not being on the website for a couple days (which could be seen if someone were to go on a weekend trip)

BUT here is the picture of the thing I found an issue with:
![image](https://user-images.githubusercontent.com/33165589/78917294-4fa0c800-7a54-11ea-8cbe-a6afb1eada07.png)

I can't remember if I started a new log or if I just clicked 'save log' on my last entry, but the start date time is for April 6th, 11:27 AM, and when I logged back on today (April 9, 2020) The **Finish Current Log** time was **23h 57m 40s** Even though it has been waiting for me to put in an end date for over three days. 

Just to make sure that it would calculate accurately despite the start and end date being so far apart, I entered an end date and it calculated corrected!
![image](https://user-images.githubusercontent.com/33165589/78917865-1fa5f480-7a55-11ea-986e-c49dc15d7317.png)

**Comment by mjllewelyn** [comment]
My guess is that the website goes to sleep after a certain amount of inactivity (I can't remember how long), so it could be that it was only counting when the website was awake, and not when it was asleep.
@dhuey Do you have any thoughts?

**Comment by dhuey** [comment]
Currently, the Finish Current Log maxes out at 24 hours. You can see that the time is correct (i.e., 11:27 - 11:26 = 23h 59m), but we have it hard-coded to not display days.

I think it would be good to show days if the current log has gone on for longer than a day, so that people know they have an old log they need to cancel or finish with the appropriate time.

**Comment by dhuey** [comment]
Fixed this in fe5af6cb
