### ISSUE TITLE
Start a log with start date in future

### ISSUE THREAD

**Issue by mjllewelyn** [EnVisageConsulting/timelog#52]
I don't know if this is ok, but you are able to start a log with a start date in the future. Right now the validations only check if the end date > start date and end date < today (end date in the past) which are the validations you need if you have both start and end date. However it's not good enough if you only have the start date. I'm not sure that this is ok as it doesn't make sense to start a log for the future. What are your thoughts?

**Comment by dhuey** [comment]
Yeah, I don't think there's any reason to be able to start a log in the future.

Although, if the end date has to be after the start date and the end date has to be in the past, is there any possible way a log could be saved with a start date in the future? I think if it can't be saved, it probably doesn't really warrant going in and adding another validation.

**Comment by mjllewelyn** [comment]
That does make sense. There is no way to save it with the validations in there already
