### ISSUE TITLE
Add Save and Start new log for current time

### ISSUE THREAD

**Issue by mjllewelyn** [EnVisageConsulting/timelog#58]
Just a thought, not a huge thing, but when I leave for lunch and come back the only option is to start new log with the end time of the last log. It's simple just to click set start time, but it might be more convenient if there was a way to have it be for the current time.

**Comment by dhuey** [comment]
For this, we can just add a "Start new log" if there isn't one in progress to the log/show page. In this situation, people should just "Save log" and then start a new one

**Comment by mjllewelyn** [comment]
How about something like this:
<img width="985" alt="Screen Shot 2020-05-22 at 11 29 54 AM" src="https://user-images.githubusercontent.com/29954923/82689132-9e2eae00-9c1f-11ea-9700-a092a3870777.png">

**Comment by dhuey** [comment]
The buttons are not working for me. I would check on the paths.

**Comment by dhuey** [comment]
Actually, looks like something on my end.
