### ISSUE TITLE
When session expires, redirect to login

### ISSUE THREAD

**Issue by dhuey** [EnVisageConsulting/timelog#63]
I got the error page when my session expired. It should take me back to the login screen rather than erroring

**Comment by mjllewelyn** [comment]
I looked into this, and it seems like it's not so much a session thing (I couldn't find a timeout, plus my session has never expired) as it is a "you are not authorized" error. I tried logging out and accessing a page I was just at and got this page:
<img width="1105" alt="Screen Shot 2020-05-22 at 10 49 33 AM" src="https://user-images.githubusercontent.com/29954923/82685542-fcf12900-9c19-11ea-8d0e-b9eef6172b02.png">
I'm not sure if this is the issue, or another issue, but needs to get fixed anyway.
