### ISSUE TITLE
Invalid Date if no space between time and AM/PM

### ISSUE THREAD

**Issue by mjllewelyn** [EnVisageConsulting/timelog#64]
I noticed that it doesn't accept a date that doesn't have a space between AM/PM (05/21/2020 9:19AM). I don't know how big of an issue this is, but when I put either date in this format, then click save, it takes the date and makes it blank. The total time still works as expected so someone would assume that it was working correctly and then don't realize it's not until they click save

**Comment by dhuey** [comment]
JS validations won't work currently because of the bugginess with the datetimepicker. It would be nice if the entered time wasn't lost when it kicked back for being invalid, though I don't feel like this is a huge issue. I'm okay with hammering home entering in time in the correct format :)
