### ISSUE TITLE
Personal Report - Have logs descend by date, ascend by time

### ISSUE THREAD

**Issue by mjllewelyn** [EnVisageConsulting/timelog#82]
Right now if you have it be descending, it's descending by both date and time and it would be better to be descending by date, and ascending by time.

**Comment by agaug** [comment]
@mjllewelyn 

When I click 'descending' it's descending by date and descending by time instead of descending by date and ascending by time.

![image](https://user-images.githubusercontent.com/33165589/84408644-02ff7780-abd2-11ea-8ca0-c96c75d90b32.png)
